import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import api, { assetsAPI } from '../services/api';
import LocationSelector from '../components/LocationSelector';
import CategorySelector from '../components/CategorySelector';
import AssetIDPreview from '../components/AssetIDPreview';
import QRCodeGenerator from '../components/QRCodeGenerator';
import './AssetsManagement.css';

function AssetsManagementEnhanced() {
  const navigate = useNavigate();
  const [assets, setAssets] = useState([]);
  const [staff, setStaff] = useState([]);
  const [companies, setCompanies] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showAddModal, setShowAddModal] = useState(false);
  const [showViewModal, setShowViewModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [selectedAsset, setSelectedAsset] = useState(null);
  const [currentTab, setCurrentTab] = useState('basic');
  
  // Filters
  const [filters, setFilters] = useState({
    year: 'all',
    category: 'all',
    location: 'all',
    status: 'all'
  });

  // Form data for new asset
  const [formData, setFormData] = useState({
    // Basic Information - Location Hierarchy
    main_category: '',
    category_code: '',
    country_id: null,
    province_id: null,
    company_id: null,
    country_code: '',
    province_code: '',
    company_code: '',
    
    // Asset Details
    purchase_date: '',
    status: 'Available',
    category: '',
    brand: '',
    model: '',
    model_name: '',
    serial_number: '',
    sn_type: '',
    description: '',
    
    // Technical Specs
    processor: '',
    ram: '',
    storage: '',
    graphics: '',
    display: '',
    os: '',
    
    // Assignment
    assigned_to: '',
    department: '',
    assignment_date: '',
    
    // Purchase Info
    supplier: '',
    purchase_cost: '',
    warranty_end: '',
    invoice_number: ''
  });

  useEffect(() => {
    loadAssets();
  }, [filters]);

  const loadAssets = async () => {
    try {
      setLoading(true);
      const [assetsRes, staffRes, companiesRes] = await Promise.all([
        assetsAPI.getAll(),
        api.get('/staff/'),
        api.get('/companies/')
      ]);
      setAssets(assetsRes.data || []);
      setStaff(staffRes.data || []);
      setCompanies(companiesRes.data || []);
    } catch (error) {
      console.error('Error loading assets:', error);
      setAssets([]);
    } finally {
      setLoading(false);
    }
  };

  const handleFilterChange = (filterName, value) => {
    setFilters(prev => ({ ...prev, [filterName]: value }));
  };

  const clearFilters = () => {
    setFilters({
      year: 'all',
      category: 'all',
      location: 'all',
      status: 'all'
    });
  };

  const handleLocationChange = (locationData) => {
    setFormData(prev => ({
      ...prev,
      country_id: locationData.countryId,
      province_id: locationData.provinceId,
      company_id: locationData.companyId,
      country_code: locationData.countryCode,
      province_code: locationData.provinceCode,
      company_code: locationData.companyCode
    }));
  };

  const handleCategoryChange = (categoryData) => {
    setFormData(prev => ({
      ...prev,
      main_category: categoryData.categoryName,
      category_code: categoryData.categoryCode
    }));
  };

  const handleInputChange = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      // The asset ID will be generated by the backend
      await assetsAPI.create(formData);
      setShowAddModal(false);
      resetForm();
      loadAssets();
      alert('Asset created successfully!');
    } catch (error) {
      console.error('Error creating asset:', error);
      alert('Error creating asset. Please try again.');
    }
  };

  const resetForm = () => {
    setFormData({
      main_category: '',
      category_code: '',
      country_id: null,
      province_id: null,
      company_id: null,
      country_code: '',
      province_code: '',
      company_code: '',
      purchase_date: '',
      status: 'Available',
      category: '',
      brand: '',
      model: '',
      model_name: '',
      serial_number: '',
      sn_type: '',
      description: '',
      processor: '',
      ram: '',
      storage: '',
      graphics: '',
      display: '',
      os: '',
      assigned_to: '',
      department: '',
      assignment_date: '',
      supplier: '',
      purchase_cost: '',
      warranty_end: '',
      invoice_number: ''
    });
    setCurrentTab('basic');
  };

  const handleView = async (assetId) => {
    // Navigate to detail view page
    navigate(`/assets/${assetId}`);
  };

  const handleEdit = async (assetId) => {
    // Navigate to edit form page
    navigate(`/assets/${assetId}/edit`);
  };

  const handleUpdate = async (e) => {
    e.preventDefault();
    try {
      await assetsAPI.update(selectedAsset.assetid, formData);
      setShowEditModal(false);
      setSelectedAsset(null);
      resetForm();
      loadAssets();
      alert('Asset updated successfully!');
    } catch (error) {
      console.error('Error updating asset:', error);
      alert('Error updating asset. Please try again.');
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this asset?')) {
      try {
        await assetsAPI.delete(id);
        loadAssets();
        alert('Asset deleted successfully!');
      } catch (error) {
        console.error('Error deleting asset:', error);
        alert('Error deleting asset.');
      }
    }
  };

  const getStatusBadgeClass = (status) => {
    const statusMap = {
      'Available': 'status-available',
      'In Use': 'status-in-use',
      'Maintenance': 'status-maintenance',
      'Retired': 'status-retired',
      'Disposed': 'status-disposed'
    };
    return statusMap[status] || 'status-default';
  };

  const filteredAssets = assets.filter(asset => {
    const assetId = asset.assetcode || asset.asset_id || '';
    if (filters.year !== 'all' && !assetId.includes(filters.year)) return false;
    const categoryName = asset.main_category_name || asset.main_category || asset.category || '';
    if (filters.category !== 'all' && categoryName !== filters.category) return false;
    const locationName = asset.location_name || asset.location || '';
    if (filters.location !== 'all' && locationName !== filters.location) return false;
    const statusName = asset.status_name || asset.status || '';
    if (filters.status !== 'all' && statusName !== filters.status) return false;
    return true;
  });

  const getCurrentLocation = (asset) => {
    if (!asset.assignedto) return 'Unassigned';
    const assignedStaff = staff.find(s => s.staffid === asset.assignedto);
    if (!assignedStaff) return 'Unassigned';
    const company = companies.find(c => c.companyid === assignedStaff.companyid);
    return company?.companyname || 'Unassigned';
  };

  const renderTabContent = () => {
    const isEditMode = showEditModal && selectedAsset;
    
    switch (currentTab) {
      case 'basic':
        return (
          <div className="tab-content">
            <h3>Basic Information</h3>
            
            {/* Asset ID Preview - Show existing ID in edit mode */}
            {isEditMode ? (
              <div className="asset-id-display-edit">
                <div className="existing-asset-id">
                  <h4>Asset ID (Cannot be changed)</h4>
                  <div className="asset-id-value">{selectedAsset.assetcode}</div>
                  <p className="asset-id-note">
                    <span>🔒</span> Asset ID is locked after creation to maintain data integrity
                  </p>
                </div>
              </div>
            ) : (
              <AssetIDPreview
                mainCategory={formData.main_category}
                countryId={formData.country_id}
                provinceId={formData.province_id}
                companyId={formData.company_id}
                purchaseDate={formData.purchase_date}
              />
            )}

            {/* Main Category - Read-only in edit mode */}
            <div className="form-group">
              <label>Main Category <span className="required">*</span></label>
              {isEditMode ? (
                <div className="readonly-field">
                  <input
                    type="text"
                    value={formData.main_category || 'N/A'}
                    readOnly
                    className="form-control readonly"
                  />
                  <small className="readonly-note">
                    <span>🔒</span> Cannot be changed - used to generate Asset ID
                  </small>
                </div>
              ) : (
                <CategorySelector
                  value={formData.main_category}
                  onChange={handleCategoryChange}
                  required={true}
                />
              )}
            </div>

            {/* Location Hierarchy - Read-only in edit mode */}
            <div className="form-group">
              <label>Location <span className="required">*</span></label>
              {isEditMode ? (
                <div className="readonly-field">
                  <div className="location-readonly">
                    <div className="location-item">
                      <span className="location-label">Country:</span>
                      <span className="location-value">ID: {selectedAsset.countryid}</span>
                    </div>
                    <div className="location-item">
                      <span className="location-label">Province:</span>
                      <span className="location-value">ID: {selectedAsset.provinceid}</span>
                    </div>
                    <div className="location-item">
                      <span className="location-label">Company:</span>
                      <span className="location-value">ID: {selectedAsset.companyid}</span>
                    </div>
                  </div>
                  <small className="readonly-note">
                    <span>🔒</span> Cannot be changed - used to generate Asset ID
                  </small>
                </div>
              ) : (
                <LocationSelector
                  value={{
                    countryId: formData.country_id,
                    provinceId: formData.province_id,
                    companyId: formData.company_id
                  }}
                  onChange={handleLocationChange}
                  required={true}
                />
              )}
            </div>

            {/* Purchase Date - Read-only in edit mode */}
            <div className="form-group">
              <label>Purchase Date <span className="required">*</span></label>
              {isEditMode ? (
                <div className="readonly-field">
                  <input
                    type="text"
                    value={selectedAsset.purchasedate ? new Date(selectedAsset.purchasedate).toLocaleDateString() : 'N/A'}
                    readOnly
                    className="form-control readonly"
                  />
                  <small className="readonly-note">
                    <span>🔒</span> Cannot be changed - used to generate Asset ID
                  </small>
                </div>
              ) : (
                <input
                  type="date"
                  value={formData.purchase_date}
                  onChange={(e) => handleInputChange('purchase_date', e.target.value)}
                  required
                />
              )}
            </div>

            {/* Asset Details - These can be edited */}
            <div className="form-row">
              <div className="form-group">
                <label>Status</label>
                <select
                  value={formData.status}
                  onChange={(e) => handleInputChange('status', e.target.value)}
                >
                  <option value="Available">Available</option>
                  <option value="In Use">In Use</option>
                  <option value="Maintenance">Maintenance</option>
                  <option value="Retired">Retired</option>
                  <option value="Disposed">Disposed</option>
                </select>
              </div>

              <div className="form-group">
                <label>Brand</label>
                <input
                  type="text"
                  value={formData.brand}
                  onChange={(e) => handleInputChange('brand', e.target.value)}
                  placeholder="e.g., Dell, HP, Lenovo"
                />
              </div>
            </div>

            <div className="form-row">
              <div className="form-group">
                <label>Model</label>
                <input
                  type="text"
                  value={formData.model}
                  onChange={(e) => handleInputChange('model', e.target.value)}
                  placeholder="e.g., Latitude 5420"
                />
              </div>

              <div className="form-group">
                <label>Model Name</label>
                <input
                  type="text"
                  value={formData.model_name}
                  onChange={(e) => handleInputChange('model_name', e.target.value)}
                  placeholder="Full model name"
                />
              </div>
            </div>

            <div className="form-row">
              <div className="form-group">
                <label>Serial Number</label>
                <input
                  type="text"
                  value={formData.serial_number}
                  onChange={(e) => handleInputChange('serial_number', e.target.value)}
                  placeholder="Serial number"
                />
              </div>

              <div className="form-group">
                <label>SN Type</label>
                <input
                  type="text"
                  value={formData.sn_type}
                  onChange={(e) => handleInputChange('sn_type', e.target.value)}
                  placeholder="Serial number type"
                />
              </div>
            </div>

            <div className="form-group">
              <label>Description</label>
              <textarea
                value={formData.description}
                onChange={(e) => handleInputChange('description', e.target.value)}
                rows="3"
                placeholder="Asset description"
              />
            </div>
          </div>
        );

      case 'technical':
        return (
          <div className="tab-content">
            <h3>Technical Specifications</h3>
            
            <div className="form-row">
              <div className="form-group">
                <label>Processor</label>
                <input
                  type="text"
                  value={formData.processor}
                  onChange={(e) => handleInputChange('processor', e.target.value)}
                  placeholder="e.g., Intel Core i7-11800H"
                />
              </div>

              <div className="form-group">
                <label>RAM</label>
                <input
                  type="text"
                  value={formData.ram}
                  onChange={(e) => handleInputChange('ram', e.target.value)}
                  placeholder="e.g., 16GB DDR4"
                />
              </div>
            </div>

            <div className="form-row">
              <div className="form-group">
                <label>Storage</label>
                <input
                  type="text"
                  value={formData.storage}
                  onChange={(e) => handleInputChange('storage', e.target.value)}
                  placeholder="e.g., 512GB SSD"
                />
              </div>

              <div className="form-group">
                <label>Graphics</label>
                <input
                  type="text"
                  value={formData.graphics}
                  onChange={(e) => handleInputChange('graphics', e.target.value)}
                  placeholder="e.g., NVIDIA RTX 3060"
                />
              </div>
            </div>

            <div className="form-row">
              <div className="form-group">
                <label>Display</label>
                <input
                  type="text"
                  value={formData.display}
                  onChange={(e) => handleInputChange('display', e.target.value)}
                  placeholder="e.g., 15.6 inch FHD"
                />
              </div>

              <div className="form-group">
                <label>Operating System</label>
                <input
                  type="text"
                  value={formData.os}
                  onChange={(e) => handleInputChange('os', e.target.value)}
                  placeholder="e.g., Windows 11 Pro"
                />
              </div>
            </div>
          </div>
        );

      case 'assignment':
        return (
          <div className="tab-content">
            <h3>Assignment Information</h3>
            
            <div className="form-group">
              <label>Assigned To</label>
              <input
                type="text"
                value={formData.assigned_to}
                onChange={(e) => handleInputChange('assigned_to', e.target.value)}
                placeholder="Employee name"
              />
            </div>

            <div className="form-group">
              <label>Department</label>
              <input
                type="text"
                value={formData.department}
                onChange={(e) => handleInputChange('department', e.target.value)}
                placeholder="Department name"
              />
            </div>

            <div className="form-group">
              <label>Assignment Date</label>
              <input
                type="date"
                value={formData.assignment_date}
                onChange={(e) => handleInputChange('assignment_date', e.target.value)}
              />
            </div>
          </div>
        );

      case 'purchase':
        return (
          <div className="tab-content">
            <h3>Purchase Information</h3>
            
            <div className="form-group">
              <label>Supplier</label>
              <input
                type="text"
                value={formData.supplier}
                onChange={(e) => handleInputChange('supplier', e.target.value)}
                placeholder="Supplier name"
              />
            </div>

            <div className="form-row">
              <div className="form-group">
                <label>Purchase Cost</label>
                <input
                  type="number"
                  value={formData.purchase_cost}
                  onChange={(e) => handleInputChange('purchase_cost', e.target.value)}
                  placeholder="0.00"
                  step="0.01"
                />
              </div>

              <div className="form-group">
                <label>Invoice Number</label>
                <input
                  type="text"
                  value={formData.invoice_number}
                  onChange={(e) => handleInputChange('invoice_number', e.target.value)}
                  placeholder="Invoice #"
                />
              </div>
            </div>

            <div className="form-group">
              <label>Warranty End Date</label>
              <input
                type="date"
                value={formData.warranty_end}
                onChange={(e) => handleInputChange('warranty_end', e.target.value)}
              />
            </div>
          </div>
        );

      case 'qrcode':
        return (
          <div className="tab-content">
            <h3>QR Code & Label</h3>
            <p className="tab-info">
              QR code will be generated automatically after the asset is created.
              You can generate and print it from the asset detail page.
            </p>
            <div className="qr-preview-placeholder">
              <div className="qr-icon">🔲</div>
              <div>QR Code will appear here after saving</div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="assets-management">
      <div className="page-header">
        <h1>Asset Management</h1>
        <button className="btn btn-primary" onClick={() => navigate('/assets/new')}>
          + Add New Asset
        </button>
      </div>

      {/* Filters Section */}
      <div className="filters-section">
        <div className="filter-group">
          <label>Year</label>
          <select value={filters.year} onChange={(e) => handleFilterChange('year', e.target.value)}>
            <option value="all">All Years</option>
            <option value="26">2026</option>
            <option value="25">2025</option>
            <option value="24">2024</option>
          </select>
        </div>

        <div className="filter-group">
          <label>Category</label>
          <select value={filters.category} onChange={(e) => handleFilterChange('category', e.target.value)}>
            <option value="all">All Categories</option>
            <option value="Computer">Computer</option>
            <option value="Laptop">Laptop</option>
            <option value="Monitor">Monitor</option>
            <option value="Printer">Printer</option>
          </select>
        </div>

        <div className="filter-group">
          <label>Status</label>
          <select value={filters.status} onChange={(e) => handleFilterChange('status', e.target.value)}>
            <option value="all">All Status</option>
            <option value="Available">Available</option>
            <option value="In Use">In Use</option>
            <option value="Maintenance">Maintenance</option>
            <option value="Retired">Retired</option>
          </select>
        </div>

        <button className="btn btn-secondary" onClick={clearFilters}>
          Clear Filters
        </button>
      </div>

      {/* Assets Table */}
      <div className="assets-table-container">
        <div className="table-info">
          Showing {filteredAssets.length} of {assets.length} assets
        </div>
        
        {loading ? (
          <div className="loading">Loading assets...</div>
        ) : (
          <table className="assets-table">
            <thead>
              <tr>
                <th>ASSET ID</th>
                <th>ASSET NAME</th>
                <th>CATEGORY</th>
                <th>LOCATION</th>
                <th>CURRENT LOCATION</th>
                <th>STOCK LOCATION</th>
                <th>STATUS</th>
                <th>ASSIGNED TO</th>
                <th>ACTIONS</th>
              </tr>
            </thead>
            <tbody>
              {filteredAssets.length === 0 ? (
                <tr>
                  <td colSpan="9" className="no-data">No assets found</td>
                </tr>
              ) : (
                filteredAssets.map(asset => (
                  <tr key={asset.assetid || asset.id}>
                    <td className="asset-id">{asset.assetcode || asset.asset_id || 'N/A'}</td>
                    <td>{asset.assetname || asset.name || asset.model_name || 'N/A'}</td>
                    <td>
                      {(asset.main_category_name || asset.main_category) ? (
                        <span className="category-badge">{asset.main_category_name || asset.main_category}</span>
                      ) : '—'}
                    </td>
                    <td>{asset.location_name || asset.location || asset.company_name || 'Unknown'}</td>
                    <td>{getCurrentLocation(asset)}</td>
                    <td>{asset.stock_location_name || 'Not on stock'}</td>
                    <td>
                      <span className={`status-badge ${getStatusBadgeClass(asset.status_name || asset.status)}`}>
                        {asset.status_name || asset.status || 'Available'}
                      </span>
                    </td>
                    <td>{asset.assigned_user_name || asset.assigned_to || 'Unassigned'}</td>
                    <td className="actions-cell">
                      <button 
                        className="btn-icon btn-view" 
                        title="View" 
                        onClick={() => handleView(asset.assetid || asset.id)}
                      >
                        <span>👁️</span>
                      </button>
                      <button 
                        className="btn-icon btn-edit" 
                        title="Edit" 
                        onClick={() => handleEdit(asset.assetid || asset.id)}
                      >
                        <span>✏️</span>
                      </button>
                      <button 
                        className="btn-icon btn-delete" 
                        title="Delete"
                        onClick={() => handleDelete(asset.assetid || asset.id)}
                      >
                        <span>🗑️</span>
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        )}
      </div>

      {/* Add Asset Modal */}
      {showAddModal && (
        <div className="modal-overlay" onClick={() => setShowAddModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Add New Asset</h2>
              <button className="modal-close" onClick={() => setShowAddModal(false)}>×</button>
            </div>

            <div className="modal-tabs">
              <button
                className={`tab-btn ${currentTab === 'basic' ? 'active' : ''}`}
                onClick={() => setCurrentTab('basic')}
              >
                1. Basic Info
              </button>
              <button
                className={`tab-btn ${currentTab === 'technical' ? 'active' : ''}`}
                onClick={() => setCurrentTab('technical')}
              >
                2. Technical
              </button>
              <button
                className={`tab-btn ${currentTab === 'assignment' ? 'active' : ''}`}
                onClick={() => setCurrentTab('assignment')}
              >
                3. Assignment
              </button>
              <button
                className={`tab-btn ${currentTab === 'purchase' ? 'active' : ''}`}
                onClick={() => setCurrentTab('purchase')}
              >
                4. Purchase
              </button>
              <button
                className={`tab-btn ${currentTab === 'qrcode' ? 'active' : ''}`}
                onClick={() => setCurrentTab('qrcode')}
              >
                5. QR Code
              </button>
            </div>

            <form onSubmit={handleSubmit}>
              <div className="modal-body">
                {renderTabContent()}
              </div>

              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setShowAddModal(false)}>
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary">
                  Save Asset
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Edit Asset Modal */}
      {showEditModal && selectedAsset && (
        <div className="modal-overlay" onClick={() => { setShowEditModal(false); setSelectedAsset(null); resetForm(); }}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Edit Asset: {selectedAsset.assetcode}</h2>
              <button className="modal-close" onClick={() => { setShowEditModal(false); setSelectedAsset(null); resetForm(); }}>×</button>
            </div>

            <div className="modal-tabs">
              <button
                className={`tab-btn ${currentTab === 'basic' ? 'active' : ''}`}
                onClick={() => setCurrentTab('basic')}
              >
                1. Basic Info
              </button>
              <button
                className={`tab-btn ${currentTab === 'technical' ? 'active' : ''}`}
                onClick={() => setCurrentTab('technical')}
              >
                2. Technical
              </button>
              <button
                className={`tab-btn ${currentTab === 'assignment' ? 'active' : ''}`}
                onClick={() => setCurrentTab('assignment')}
              >
                3. Assignment
              </button>
              <button
                className={`tab-btn ${currentTab === 'purchase' ? 'active' : ''}`}
                onClick={() => setCurrentTab('purchase')}
              >
                4. Purchase
              </button>
              <button
                className={`tab-btn ${currentTab === 'qrcode' ? 'active' : ''}`}
                onClick={() => setCurrentTab('qrcode')}
              >
                5. QR Code
              </button>
            </div>

            <form onSubmit={handleUpdate}>
              <div className="modal-body">
                {renderTabContent()}
              </div>

              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => { setShowEditModal(false); setSelectedAsset(null); resetForm(); }}>
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary">
                  Update Asset
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* View Asset Modal */}
      {showViewModal && selectedAsset && (
        <div className="modal-overlay" onClick={() => { setShowViewModal(false); setSelectedAsset(null); }}>
          <div className="modal-content view-modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Asset Details</h2>
              <button className="modal-close" onClick={() => { setShowViewModal(false); setSelectedAsset(null); }}>×</button>
            </div>

            <div className="modal-body view-content">
              {/* Asset ID and QR Code */}
              <div className="view-section highlight-section">
                <div className="asset-id-display">
                  <h3>{selectedAsset.assetcode}</h3>
                  <p className="asset-name">{selectedAsset.assetname}</p>
                </div>
                {selectedAsset.qrcode && (
                  <div className="qr-code-display">
                    <img src={selectedAsset.qrcode} alt="Asset QR Code" />
                  </div>
                )}
              </div>

              {/* Basic Information */}
              <div className="view-section">
                <h4>Basic Information</h4>
                <div className="view-grid">
                  <div className="view-field">
                    <label>Status:</label>
                    <span className={`status-badge ${getStatusBadgeClass(selectedAsset.status)}`}>
                      {selectedAsset.status || 'Available'}
                    </span>
                  </div>
                  <div className="view-field">
                    <label>Manufacturer:</label>
                    <span>{selectedAsset.manufacturer || 'N/A'}</span>
                  </div>
                  <div className="view-field">
                    <label>Model:</label>
                    <span>{selectedAsset.modelnumber || 'N/A'}</span>
                  </div>
                  <div className="view-field">
                    <label>Serial Number:</label>
                    <span>{selectedAsset.serialnumber || 'N/A'}</span>
                  </div>
                </div>
              </div>

              {/* Location Information */}
              <div className="view-section">
                <h4>Location Information</h4>
                <div className="view-grid">
                  <div className="view-field">
                    <label>Country ID:</label>
                    <span>{selectedAsset.countryid || 'N/A'}</span>
                  </div>
                  <div className="view-field">
                    <label>Province ID:</label>
                    <span>{selectedAsset.provinceid || 'N/A'}</span>
                  </div>
                  <div className="view-field">
                    <label>Company ID:</label>
                    <span>{selectedAsset.companyid || 'N/A'}</span>
                  </div>
                  <div className="view-field">
                    <label>Department ID:</label>
                    <span>{selectedAsset.departmentid || 'N/A'}</span>
                  </div>
                </div>
              </div>

              {/* Assignment Information */}
              <div className="view-section">
                <h4>Assignment Information</h4>
                <div className="view-grid">
                  <div className="view-field">
                    <label>Assigned To:</label>
                    <span>{selectedAsset.assignedto || 'Unassigned'}</span>
                  </div>
                  <div className="view-field">
                    <label>Assignment Date:</label>
                    <span>{selectedAsset.assigneddate ? new Date(selectedAsset.assigneddate).toLocaleDateString() : 'N/A'}</span>
                  </div>
                </div>
              </div>

              {/* Financial Information */}
              <div className="view-section">
                <h4>Financial Information</h4>
                <div className="view-grid">
                  <div className="view-field">
                    <label>Purchase Date:</label>
                    <span>{selectedAsset.purchasedate ? new Date(selectedAsset.purchasedate).toLocaleDateString() : 'N/A'}</span>
                  </div>
                  <div className="view-field">
                    <label>Purchase Price:</label>
                    <span>{selectedAsset.purchaseprice ? `$${selectedAsset.purchaseprice.toFixed(2)}` : 'N/A'}</span>
                  </div>
                  <div className="view-field">
                    <label>Current Value:</label>
                    <span>{selectedAsset.currentvalue ? `$${selectedAsset.currentvalue.toFixed(2)}` : 'N/A'}</span>
                  </div>
                  <div className="view-field">
                    <label>Warranty Expiry:</label>
                    <span>{selectedAsset.warrantyexpiry ? new Date(selectedAsset.warrantyexpiry).toLocaleDateString() : 'N/A'}</span>
                  </div>
                </div>
              </div>

              {/* Additional Information */}
              {selectedAsset.notes && (
                <div className="view-section">
                  <h4>Notes</h4>
                  <p className="notes-text">{selectedAsset.notes}</p>
                </div>
              )}

              {/* Metadata */}
              <div className="view-section metadata-section">
                <h4>Record Information</h4>
                <div className="view-grid">
                  <div className="view-field">
                    <label>Created:</label>
                    <span>{new Date(selectedAsset.createdat).toLocaleString()}</span>
                  </div>
                  <div className="view-field">
                    <label>Last Updated:</label>
                    <span>{new Date(selectedAsset.updatedat).toLocaleString()}</span>
                  </div>
                  <div className="view-field">
                    <label>Created By:</label>
                    <span>User ID: {selectedAsset.createdby || 'N/A'}</span>
                  </div>
                  <div className="view-field">
                    <label>Active:</label>
                    <span>{selectedAsset.isactive ? 'Yes' : 'No'}</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="modal-footer">
              <button 
                type="button" 
                className="btn btn-secondary" 
                onClick={() => { setShowViewModal(false); setSelectedAsset(null); }}
              >
                Close
              </button>
              <button 
                type="button" 
                className="btn btn-primary" 
                onClick={() => {
                  setShowViewModal(false);
                  handleEdit(selectedAsset.assetid);
                }}
              >
                Edit Asset
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default AssetsManagementEnhanced;
